name 'vimrc'
maintainer 'Taylor Monacelli'
maintainer_email 'taylormonacelli@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures vimrc'
long_description 'Installs/Configures vimrc'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'macos'
supports 'windows'
issues_url 'https://github.com/taylormonacelli/vimrc/issues'
source_url 'https://github.com/taylormonacelli/vimrc'
license 'Apache-2.0'
depends 'chocolatey'
